### ISSUE TITLE
BoP Alps generate a bit strange

### ISSUE THREAD

**Issue by bogger33** [superfluke/hexlands#15]
I kinda like it, to be honest

![2018-06-22_21 30 02](https://user-images.githubusercontent.com/10445063/41811570-7961ea8a-7712-11e8-99b1-71571a3c76fd.png)
![2018-06-23_18 21 09](https://user-images.githubusercontent.com/10445063/41811577-86bb5554-7712-11e8-95ff-f5b67afacff6.png)

AlpsFoothills generate fine

![2018-06-22_21 30 40](https://user-images.githubusercontent.com/10445063/41811595-e49d6266-7712-11e8-96f8-e295d7b4d914.png)

Seed: 
![2018-06-23_18 26 13](https://user-images.githubusercontent.com/10445063/41811606-05a66476-7713-11e8-8d8f-4b93048c14a6.png)

Config:

https://gist.github.com/bogger33/088b5141bc82db27667aa30dae89bc7e

It's FTB revelations 2.1.0, with some extra mods

**Comment by superfluke** [comment]
well that's.... interesting. Doesn't seem to be as much of a bug as it is just what happens when the biome height is set absurdly high like the alps are. Changed things a bit so alps are still absurdly tall, but not game-breakingly tall
![image](https://user-images.githubusercontent.com/20022336/41815351-26c8342c-7736-11e8-9653-d5cdaff468b4.png)
