### ISSUE TITLE
[Request] More customization config options

### ISSUE THREAD

**Issue by SextupleTap** [superfluke/hexlands#25]
A Boolean to override the set rim blocks to instead use the surface block of the biome/terrain/y-level (defaults to false).

A config section that accepts an integer as the rim width (defaults is same as it is "post" this potential addition).

A Boolean to disable all (registered) wet biomes (defaults to false).

A config section that accepts a string of Biomes to never generate (empty by default, uses the same system as registering wet biomes).

A Boolean that overrides rim heights and has the rim flush with the terrain (e.g. if the rim goes into a mountain it won't cut it off it will "go" with it smoothly, is set to false by default).

I would like to hear feedback on what you think of these and if you want to consider adding a few!

Lastly, bug-fix:
In wet biomes like rivers, or BOP kelp forest/coral reef etc.
When you have the rim set to "go to bedrock" mode, when the water generates it overrides the rim blocks and leaves floating rim blocks above the water (the floating blocks were fixed in 1.7.1 but the water still overrides the rim).

**Comment by superfluke** [comment]
1. Try using minecraft:stone as the rim block, it'll be replaced by the biome top block
2. I can look into that
3. Do you mean remove them from world gen? I can't do that, or it's outside the scope of this mod. The Some Like It Dry mod can reduce or remove oceans. 
4. See point 3, check out mods like biome tweaker or dimensional control for that. 
5. I'm not quite sure what you're asking here. If you want the rim flush with the hex rather than one block above, that's what the sunken biome config is for.
6. Yeah that shouldn't be happening, I'll look into it. Also note that the coral_reef and kelp_forest biomes are added to the sunken biome list by default in the newest version. If you config file what generated before, you'll need to add those biomes yourself (or delete the config file to let it regenerate).

**Comment by SextupleTap** [comment]
Can the Boolean still be an opinion though (false by default)? How it looks is subjective to each person in my opinion.

**Comment by superfluke** [comment]
I can appreciate the look is subjective, but adding that in isn't as easy as just throwing in an extra config option. Parts of the terrain height code are built around the fact that the edges are all the same height, and I don't plan on spending time rewriting that for an idea I don't think looks good.
